# Generated by Django 4.1.2 on 2022-10-16 12:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moment",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
